### ISSUE TITLE
Capacitor v7.0 incompatibility

### ISSUE THREAD

**Issue by NorthFred** [Cap-go/capacitor-native-market#51]
When upgrading from Capacitor 6 to 7, following errors (and warnings) occur during the building process:

```
To suppress this warning, set android.javaCompile.suppressSourceTargetDeprecationWarning=true in gradle.properties.
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
C:\Project\node_modules\@capgo\native-market\android\src\main\java\com\getcapacitor\community\nativemarket\NativeMarket.java:6: warning: [deprecation] NativePlugin in com.getcapacitor has been deprecated
import com.getcapacitor.NativePlugin;
                       ^
C:\Project\node_modules\@capgo\native-market\android\src\main\java\com\getcapacitor\community\nativemarket\NativeMarket.java:18: warning: [deprecation] hasOption(String) in PluginCall has been deprecated
      if (call.hasOption("appId")) {
              ^
C:\Project\node_modules\@capgo\native-market\android\src\main\java\com\getcapacitor\community\nativemarket\NativeMarket.java:34: error: cannot find symbol
      call.error(ex.getLocalizedMessage());
          ^
  symbol:   method error(String)
  location: variable call of type PluginCall
C:\Project\node_modules\@capgo\native-market\android\src\main\java\com\getcapacitor\community\nativemarket\NativeMarket.java:41: warning: [deprecation] hasOption(String) in PluginCall has been deprecated
      if (call.hasOption("devId")) {
              ^
C:\Project\node_modules\@capgo\native-market\android\src\main\java\com\getcapacitor\community\nativemarket\NativeMarket.java:57: error: cannot find symbol
      call.error(ex.getLocalizedMessage());
          ^
  symbol:   method error(String)
  location: variable call of type PluginCall
C:\Project\node_modules\@capgo\native-market\android\src\main\java\com\getcapacitor\community\nativemarket\NativeMarket.java:64: warning: [deprecation] hasOption(String) in PluginCall has been deprecated
      if (call.hasOption("name")) {
              ^
C:\Project\node_modules\@capgo\native-market\android\src\main\java\com\getcapacitor\community\nativemarket\NativeMarket.java:80: error: cannot find symbol
      call.error(ex.getLocalizedMessage());
          ^
  symbol:   method error(String)
  location: variable call of type PluginCall
C:\Project\node_modules\@capgo\native-market\android\src\main\java\com\getcapacitor\community\nativemarket\NativeMarket.java:87: warning: [deprecation] hasOption(String) in PluginCall has been deprecated
      if (call.hasOption("editorChoice")) {
              ^
C:\Project\node_modules\@capgo\native-market\android\src\main\java\com\getcapacitor\community\nativemarket\NativeMarket.java:105: error: cannot find symbol
      call.error(ex.getLocalizedMessage());
          ^
  symbol:   method error(String)
  location: variable call of type PluginCall
C:\Project\node_modules\@capgo\native-market\android\src\main\java\com\getcapacitor\community\nativemarket\NativeMarket.java:112: warning: [deprecation] hasOption(String) in PluginCall has been deprecated
      if (call.hasOption("terms")) {
              ^
C:\Project\node_modules\@capgo\native-market\android\src\main\java\com\getcapacitor\community\nativemarket\NativeMarket.java:128: error: cannot find symbol
      call.error(ex.getLocalizedMessage());
          ^
  symbol:   method error(String)
  location: variable call of type PluginCall
5 errors
9 warnings
```

**Comment by riderx** [comment]
fixed
